import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  name: "",
  value: false,
  status: 'idle',
};

export const checkBoxSlice = createSlice({
  name: 'checkBox',
  initialState,//初期化
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // method = actions
    setChecked: (state,action) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
      state.value = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});
export const setValue = (state:any) => state.checkBox.value;

export const { setChecked } = checkBoxSlice.actions;
export default checkBoxSlice.reducer;
